      SUBROUTINE RES(T, Y, YPRIME, DEL, IRES, RPAR, IPAR)

      IMPLICIT NONE

      INTEGER IPAR(*), IRES, NSTATE
      DOUBLE PRECISION T, Y(*), YPRIME(*), DEL(*), RPAR(100)
      EXTERNAL RES_DAEPACK
      
      NSTATE = IPAR(1)

      CALL RES_DAEPACK(NSTATE, T, Y, YPRIME, DEL, IRES, RPAR, IPAR)


      END SUBROUTINE RES
